# Generated by Django 2.0.6 on 2018-07-04 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puntuacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuerpo', models.CharField(max_length=50)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntuaciones', to='App.Noticia')),
            ],
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='noticia',
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
